### ISSUE TITLE
Selenium class not callable after installing through composer

### ISSUE THREAD

**Issue by desjob** [joomla-projects/selenium-server-standalone#43]
In my use-case i would like to use the Selenium class directly from PHP, instead of using the supplied binary.
However, when you require "joomla-projects/selenium-server-standalone" in your php project, you can not use the Selenium class out-of-the-box through the composer autoloader, because the composer.json of joomla-projects/selenium-server-standalone does not have any autoload setup defined.

**Comment by yvesh** [comment]
Closed as we have a PR
